name: Deploy dongtai website v2

on:
  release:
    types: ["created"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build hugo static files
        uses: klakegg/actions-hugo@1.0.0

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}

      - name: Upload static file to oss
        run: |
          ossutil cp -rf public/ oss://dongtai-huoxian-cn/
